---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: 02_Threatfeed_V3_code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=password
 #     - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password
 #     - SUDO_PASSWORD_HASH= #optional
 #     - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/website
    volumes:
      - /docker/02_Threatfeed_v3/config-vscode:/config
      - /docker/02_Threatfeed_v3/website:/website
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      disthred-nw:
        ipv4_address: 172.18.3.11


  web-server:
    container_name: 02_Threatfeed_v3
    image: distributed-threatfeed
    restart: unless-stopped
    environment:
      - BASIC_AUTH=true
      - BASIC_AUTH_USER=myuser
      - BASIC_AUTH_PASSWORD=mypassword
    volumes:
      - /docker/02_Threatfeed_v3/website:/var/www/html
    ports:
      - "8742:80"
    networks:
      disthred-nw:
        ipv4_address: 172.18.3.12

networks:
  disthred-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.3.0/24
          gateway: 172.18.3.1